version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn cabportal.wsgi:application --bind 0.0.0.0:8000 --workers=2 --timeout 600 --reload
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/media
      - .:/home/app/web


  # Nginx Web Server Service
  nginx:
    image: nginx:1.19.0
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/staticfiles
    depends_on:
      - web
 

volumes:
  postgres-data:
  staticfiles:
  mediafiles:
